### ISSUE TITLE
Integration into u8g2 Library?

### ISSUE THREAD

**Issue by Triscus** [jgilbert20/MakernetSimple#1]
Hello there,

I want to use the MakerNet Knob with the Menu System of the [u8g2 ](https://github.com/olikraus/u8g2) Library.

Unfortunately the Menu System is not in scope of the u8g2 library and because of that it will not be developed further.

Anyhow, there is an [issue ](https://github.com/olikraus/u8g2/issues/161) generally describing how to implement it, but I am stuck at implement the object for the Makernet Knob in the C-based funtion. 

As a workaround I was thinking about emulating a common rotary, but this kinda misses the point of using the Makernet Knob. 

Any help or ideas on this are highly appreciated.

**Comment by jgilbert20** [comment]
I'm not too familiar with the U8g2 library but from the thread you linked it seems like you have to override a function called u8x8_GetMenuEvent and insert some of your own code. From your comment in the other issue, it looks like you're having trouble getting the U8G2 C bindings to find your C++ function. I suspect the issue has something to do with the way the Arduino compiler works, where it generally tried to compile the libraries first into a separate ASM file and then compile your code later. I wonder if there is a way you could use the weak binding attribute to fix this? I've never used that myself but it seems to let you define a function that can be overridden by something else by the linker later. This is a little beyond my abilities as a C++ programmer to know the fix exactly. You may have to get really deep into the internals of the Arduino build environment or else find a way to put your code entirely in the library itself rather than partially in the library or partially in Arduino IDE. I hope that helps.

**Comment by Triscus** [comment]
The hint with pragma weak helped a lot. I defined the function in the library as weak and defined my own function in the .ino. It has to be tweaked a bit, but at least it's reacting now. 

```
uint8_t u8x8_GetMenuEvent(u8x8_t *u8x8)
{
	knob.update();
	int turn = knob.positionDelta();

	switch (turn)
	{
	case 1:
		return U8X8_MSG_GPIO_MENU_UP;
	case -1:
		return U8X8_MSG_GPIO_MENU_DOWN;
	default:
		break;
	}

	Serial.println(turn);
}
```
Thank you for your help and keep up the good work, it's a really nice device you built.
